Repository zilliztech/milvus-operator, pull requests merged in 2023-11, with the labels that each got.

#34 Fix typo in readme
  README.md
Labels: documentation, approved, size/XS

#33 Supports custom mq
  apis/milvus.io/v1beta1/dependencies_types.go
  apis/milvus.io/v1beta1/milvus_webhook.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/configmaps.go
  pkg/controllers/dependencies.go
  pkg/controllers/milvus_controller.go
  pkg/controllers/status_cluster.go
  pkg/controllers/status_cluster_test.go
Labels: lgtm, approved, ci-passed, size/M

#36 Fix volumeMounts merge
  pkg/controllers/components.go
  pkg/controllers/components_test.go
Labels: lgtm, approved, ci-passed, size/M

#37 Allow setting annotations for checker job
  charts/milvus-operator/templates/job.yaml
  charts/milvus-operator/values.yaml
Labels: lgtm, approved, ci-passed, size/XS

#38 Support kafka sasl health probe
  config/samples/milvus_kafka.yaml
  pkg/controllers/conditions.go
  pkg/controllers/conditions_test.go
  pkg/controllers/status_cluster.go
  pkg/external/kafka.go
  pkg/external/kafka_test.go
  pkg/external/minio.go
Labels: lgtm, approved, ci-passed, size/L

#41 bump version, milvus default version to 2.3.3
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#46 Support --run-with-subprocess flag
  apis/milvus.io/v1beta1/components_types.go
  apis/milvus.io/v1beta1/zz_generated.deepcopy.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  go.mod
  pkg/controllers/components.go
  pkg/controllers/components_test.go
  pkg/controllers/deployment_updater.go
  test/min-mc-feature.yaml
  test/min-milvus-feature.yaml
Labels: lgtm, approved, ci-passed, size/L

#49 Fix config tool merge panic
  Makefile
  pkg/util/util.go
  pkg/util/util_test.go
  tool/merge/main.go
Labels: lgtm, approved, ci-passed, size/S

#51 Fix background deletion blocked
  pkg/controllers/milvus.go
  pkg/controllers/milvus_controller.go
  pkg/controllers/milvus_controller_test.go
  pkg/controllers/milvus_test.go
Labels: lgtm, approved, ci-passed, size/M
