Repository zilliztech/milvus-operator, pull requests merged in 2024-03, with the labels that each got.

#87 Update initContainer image when deployment rollout
  apis/milvus.io/v1beta1/components_types.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/deployment_updater_test.go
Labels: lgtm, approved, ci-passed, size/L

#91 Milvus default version to v2.3.11, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#92 Milvus default version to v2.3.12, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#94 feat: allow replicas as nil and leave it to hpa
  pkg/controllers/components.go
Labels: lgtm, approved, ci-passed, size/XS

#95 enhance: expect replicas as nil and when hpa is enabled
  pkg/controllers/components_test.go
Labels: lgtm, approved, ci-passed, size/S

#97 feat: support hpa
  apis/milvus.io/v1beta1/components_types.go
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  pkg/controllers/components.go
  pkg/controllers/components_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/deployment_updater_test.go
Labels: lgtm, approved, ci-passed, size/L

#98 bump milvus operator version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/templates/crds.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
Labels: lgtm, approved, ci-passed, size/L

#99 add force mode for component image upgrade
  apis/milvus.io/v1beta1/components_types.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/component_condition.go
  pkg/controllers/component_condition_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/status_cluster.go
  pkg/controllers/status_cluster_test.go
Labels: lgtm, approved, ci-passed, size/L

#101 Add sample for hpa, add test, bump version
  .github/workflows/ci.yml
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  config/samples/hpa.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  test/min-mc-feature.yaml
Labels: lgtm, approved, ci-passed, size/L
