Repository zilliztech/milvus-operator, pull requests merged in 2024-07, with the labels that each got.

#128 rename QueryNodeController structs as DeployController
  pkg/controllers/deploy_ctrl.go
  pkg/controllers/deploy_ctrl_test.go
  pkg/controllers/deploy_ctrl_util.go
  pkg/controllers/deploy_ctrl_util_test.go
  pkg/controllers/deploy_mode_changer.go
  pkg/controllers/deploy_mode_changer_test.go
  pkg/controllers/deployments_test.go
  pkg/controllers/milvus_controller.go
  pkg/controllers/setup.go
Labels: approved, do-not-merge/hold, size/L

#141 feat:support hostNetWork for components
  apis/milvus.io/v1beta1/components_types.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  go.mod
  go.sum
  pkg/controllers/components.go
  pkg/controllers/components_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/deployment_updater_test.go
  test/min-mc-feature.yaml
Labels: lgtm, approved, do-not-merge/hold, size/L

#146 Add EnableManualMode, fix some problems when scaling during rollout
  apis/milvus.io/v1beta1/components_types.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/component_condition.go
  pkg/controllers/deploy_ctrl.go
  pkg/controllers/deploy_ctrl_test.go
  pkg/controllers/deploy_ctrl_util.go
  pkg/controllers/deploy_ctrl_util_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/status_cluster.go
Labels: lgtm, approved, ci-passed, size/XL

#147 Add field ActiveConfigMap, to manage multiple configmap
  apis/milvus.io/v1beta1/components_types.go
  apis/milvus.io/v1beta1/label_annotations.go
  apis/milvus.io/v1beta1/milvus_types.go
  apis/milvus.io/v1beta1/milvus_types_test.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/configmaps.go
  pkg/controllers/deployment_updater.go
Labels: lgtm, approved, ci-passed, size/M

#148 upgrade controller-runtime to 0.14.6, go to 1.19
  Makefile
  apis/milvus.io/v1alpha1/zz_generated.deepcopy.go
  apis/milvus.io/v1beta1/zz_generated.deepcopy.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  config/crd/bases/milvus.io_milvusupgrades.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  deploy/manifests/deployment.yaml
  go.mod
  go.sum
  pkg/controllers/common_test.go
  pkg/controllers/component_condition_test.go
  pkg/controllers/components.go
  pkg/controllers/conditions_test.go
  pkg/controllers/configmaps_test.go
  pkg/controllers/dependencies_test.go
  pkg/controllers/deploy_ctrl_test.go
  pkg/controllers/deploy_ctrl_util_test.go
  pkg/controllers/deploy_mode_changer_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/deployments_test.go
  pkg/controllers/external_interfaces.go
  pkg/controllers/ingress_test.go
  pkg/controllers/log.go
  pkg/controllers/log_test.go
  pkg/controllers/milvus_controller_test.go
  pkg/controllers/milvus_test.go
  pkg/controllers/milvuscluster/convert_controller.go
  pkg/controllers/milvusupgrade_controller_test.go
  pkg/controllers/milvusupgrade_fsm_test.go
  pkg/controllers/podmonitor_test.go
  pkg/controllers/pvc_test.go
  pkg/controllers/rolling_mode_status_updater_test.go
  pkg/controllers/rollout_util_test.go
  pkg/controllers/services_test.go
  pkg/controllers/status_cluster_test.go
  pkg/provisioner/cert_manager_test.go
Labels: lgtm, approved, ci-passed, size/XXL

#149 Fix some bugs when change to two deploy mode
  apis/milvus.io/v1beta1/milvus_types.go
  pkg/controllers/deploy_ctrl.go
  pkg/controllers/deploy_ctrl_test.go
  pkg/controllers/deploy_ctrl_util.go
  pkg/controllers/deploy_mode_changer.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/group_runner.go
Labels: lgtm, approved, ci-passed, size/L

#150 Milvus default version to 2.4.6, bump version to 1.0.0
  .github/workflows/weekly.yml
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
  test/min-mc-alpha.yaml
  test/min-mc-kafka.yaml
  test/min-mc-mixture.yaml
  test/min-mc.yaml
Labels: lgtm, approved, ci-passed, size/L

#153 Update ci, builder to go 1.19
  .github/workflows/ci.yml
  Dockerfile
  tool.Dockerfile
Labels: lgtm, approved, ci-passed, size/XS

#151 use mixcoord & enable active standby & enable rolling update by default
  Makefile
  apis/milvus.io/v1beta1/milvus_types_test.go
  apis/milvus.io/v1beta1/milvus_webhook.go
  apis/milvus.io/v1beta1/milvus_webhook_test.go
  config/samples/milvus_cluster_4coords.yaml
  config/samples/milvus_cluster_mixcoord.yaml
  pkg/controllers/component_condition_test.go
  pkg/controllers/components_test.go
  pkg/controllers/deployments_test.go
  pkg/controllers/milvusupgrade_fsm_test.go
  pkg/controllers/status_cluster_test.go
Labels: lgtm, approved, ci-passed, size/L

#154 Fix current-querynode-label backward compatity
  apis/milvus.io/v1beta1/label_annotations.go
  apis/milvus.io/v1beta1/milvus_webhook.go
Labels: approved, do-not-merge/hold, size/XS

#155 Update docs
  .github/workflows/ci.yml
  README.md
  docs/administration/configure-milvus.md
  docs/installation/installation.md
Labels: lgtm, approved, ci-passed, size/M

#156 Bump version to 1.0.1
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
Labels: lgtm, approved, ci-passed, size/M
