Repository zilliztech/milvus-operator, pull requests merged in 2024-01, with the labels that each got.

#60 Update demo manifest, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  config/samples/cluster_demo.yaml
  config/samples/demo.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#62 longer TerminationGracePeriodSeconds
  charts/milvus-operator/templates/clusterrole.yaml
  config/rbac/role.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/component_condition.go
  pkg/controllers/component_condition_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/milvus_controller.go
  pkg/controllers/milvus_controller_test.go
  pkg/controllers/status_cluster.go
  pkg/util/k8s_client.go
  pkg/util/rest/rest_client.go
  test/hello-milvus.py
  test/mc-2.1.yaml
  test/milvus-2.1.yaml
  test/min-mc-alpha.yaml
  test/min-mc-feature.yaml
  test/min-mc-kafka.yaml
  test/min-mc-mixture.yaml
  test/min-mc.yaml
  test/min-milvus-alpha.yaml
  test/min-milvus-feature.yaml
  test/min-milvus-kafka.yaml
  test/min-milvus.yaml
  test/sit.sh
Labels: lgtm, approved, ci-passed, size/L

#65 bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#66 Update cluster deploy strategy
  pkg/controllers/components.go
  pkg/controllers/components_test.go
Labels: lgtm, approved, ci-passed, size/XS

#67 Bump version
  .github/workflows/tool-docker-image.yml
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
Labels: lgtm, approved, ci-passed, size/M

#68 Fix long stop time
  pkg/controllers/component_condition.go
  pkg/controllers/component_condition_test.go
Labels: lgtm, approved, ci-passed, size/S

#69 Bump version, default milvus version to 2.3.6
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: approved, ci-passed, size/M

#70 Fix long stop time
  pkg/util/rest/rest_client.go
Labels: lgtm, approved, ci-passed, size/XS

#71 Bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
Labels: lgtm, approved, ci-passed, size/M

#73 Milvus default version to v2.3.7, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#72 Update kafka.go to fix typo and update config for external Kafka Connection in SASL mode
  docs/administration/manage-dependencies/message-storage.md
  pkg/external/kafka.go
Labels: lgtm, approved, ci-passed, size/XS
