Repository zilliztech/milvus-operator, pull requests merged in 2024-08, with the labels that each got.

#157 deploy_mode_changer:fix typo in recovered rs name
  pkg/controllers/deploy_mode_changer.go
Labels: lgtm, approved, ci-passed, size/XS

#160 in cluster etcd use headless svc by default
  apis/milvus.io/v1beta1/milvus_webhook.go
  apis/milvus.io/v1beta1/milvus_webhook_test.go
Labels: lgtm, approved, ci-passed, size/M

#162 update milvus to 2.4.7, etcd to 3.5.14, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#161 fix: align the startup check condition with storage conf fields.
  pkg/controllers/conditions.go
  pkg/controllers/status_cluster.go
  pkg/controllers/utils.go
  pkg/external/minio.go
Labels: lgtm, approved, ci-passed, size/M

#164 go version to 1.21
  Dockerfile
  go.mod
  go.sum
  tool.Dockerfile
Labels: lgtm, approved, do-not-merge/hold, size/M

#165 milvus-default version to 2.4.8, bump version
  .github/workflows/tool-docker-image.yml
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#169 milvus default to 2.4.9, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#173 add rollout policy
  pkg/controllers/deploy_ctrl_util.go
  pkg/controllers/deploy_ctrl_util_test.go
Labels: lgtm, approved, ci-passed, size/XL

#175 bugfix for resource limit change
  pkg/controllers/deploy_ctrl_util.go
  pkg/controllers/deploy_ctrl_util_test.go
Labels: lgtm, approved, ci-passed, size/L

#176 fix metric interval
  pkg/controllers/podmonitor.go
Labels: lgtm, approved, ci-passed, size/XS

#177 bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
Labels: lgtm, approved, ci-passed, size/M
