Repository zilliztech/milvus-operator, pull requests merged in 2025-07, with the labels that each got.

#368 fix minio secretRef env
  pkg/controllers/deployments.go
  pkg/controllers/deployments_test.go
  test/min-mc-feature.yaml
Labels: lgtm, approved, ci-passed, size/M

#370 fix: secret without default mode #369
  pkg/controllers/deployment_updater.go
  pkg/controllers/deployments.go
  pkg/controllers/k8s_default_values.go
Labels: lgtm, approved, ci-passed, size/S

#380 use pidof instead of ps -C to find milvus process
  pkg/controllers/component_condition.go
Labels: lgtm, approved, ci-passed, size/XS
