Repository zilliztech/milvus-operator, pull requests merged in 2025-03, with the labels that each got.

#292 Fix typo: rename reconclie.md to reconcile.md
  docs/arch/reconcile.md
Labels: documentation, lgtm, approved, size/XS

#290 add timeout for killing pods when stopping
  pkg/controllers/component_condition.go
Labels: lgtm, approved, ci-passed, size/XS

#293 milvus default to 2.5.6, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#294 deployments: fix concurrent map read write race
  pkg/controllers/deployments.go
Labels: lgtm, approved, ci-passed, size/S

#299 milvus default to 2.5.7, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M
