Repository zilliztech/milvus-operator, pull requests merged in 2025-02, with the labels that each got.

#250 Update controller-runtime
  Dockerfile
  Makefile
  apis/milvus.io/v1alpha1/groupversion_info.go
  apis/milvus.io/v1alpha1/milvuscluster_types.go
  apis/milvus.io/v1alpha1/zz_generated.deepcopy.go
  apis/milvus.io/v1beta1/groupversion_info.go
  apis/milvus.io/v1beta1/milvus_webhook.go
  apis/milvus.io/v1beta1/milvus_webhook_test.go
  apis/milvus.io/v1beta1/milvusupgrade_webhook.go
  apis/milvus.io/v1beta1/milvusupgrade_webhook_test.go
  apis/milvus.io/v1beta1/zz_generated.deepcopy.go
  go.mod
  go.sum
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controllers/metrics.go
  test/milvus-2.4.yaml
  test/milvus-upgrade.sh
  test/patch-2.5.yaml
  tool.Dockerfile
Labels: lgtm, approved, do-not-merge/hold, size/L

#251 Standardize kind action
  .github/workflows/ci.yml
  .github/workflows/deploy-manifest.yaml
  .github/workflows/weekly.yml
  Makefile
Labels: approved, do-not-merge/hold, size/M

#254 Update controller runtime
  go.mod
  go.sum
  pkg/manager/manager.go
Labels: lgtm, approved, do-not-merge/hold, size/XL

#259 Update Prometheus Operator
  apis/milvus.io/v1beta1/components_types.go
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/L

#260 Update controller-runtime
  go.mod
  go.sum
  pkg/controllers/milvusupgrade_fsm.go
Labels: lgtm, approved, ci-passed, size/L

#258 all configmap should be updated when not in manual mode
  apis/milvus.io/v1beta1/components_types.go
  pkg/controllers/components.go
  pkg/controllers/conditions.go
  pkg/controllers/configmaps.go
  pkg/controllers/configmaps_test.go
  pkg/controllers/deploy_ctrl_factory.go
  pkg/controllers/deploy_ctrl_util_test.go
  pkg/controllers/milvus_test.go
  pkg/controllers/setup.go
  pkg/controllers/status_cluster.go
Labels: lgtm, approved, ci-passed, size/L

#264 re-generate using new controller-gen, bump version to v1.2.1
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/templates/clusterrole.yaml
  charts/milvus-operator/templates/crds.yaml
  charts/milvus-operator/values.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  config/crd/bases/milvus.io_milvusupgrades.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
Labels: lgtm, approved, size/XXL

#268 Reduce the permissions for milvus-operator-manager-role
  deploy/manifests/deployment.yaml
Labels: lgtm, approved, ci-passed, size/XS

#269 Update controller-runtime
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/M

#270 Reduce the permissions for helm chart
  charts/milvus-operator/templates/clusterrole.yaml
  config/rbac/role.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/milvus_controller.go
Labels: lgtm, approved, ci-passed, size/L

#271 Update Minio libraries
  go.mod
  go.sum
  pkg/external/iam/aliyun.go
  pkg/external/iam/tencent.go
Labels: lgtm, approved, ci-passed, size/L

#272 Update Helm Go library
  go.mod
  go.sum
Labels: lgtm, approved, ci-passed, size/L

#278 Update controller-runtime
  .github/workflows/ci.yml
  Dockerfile
  go.mod
  go.sum
  tool.Dockerfile
Labels: lgtm, approved, ci-passed, size/L

#277 Fix token renewal
  pkg/controllers/common_test.go
  pkg/controllers/dependencies.go
  pkg/controllers/dependencies_test.go
  pkg/controllers/manager_interface.go
  pkg/controllers/milvus_controller_test.go
  pkg/controllers/setup.go
Labels: lgtm, approved, ci-passed, size/L
