Repository zilliztech/milvus-operator, pull requests merged in 2025-05, with the labels that each got.

#336 Support applying custom metric labels before ingestion
  apis/milvus.io/v1beta1/components_types.go
  apis/milvus.io/v1beta1/zz_generated.deepcopy.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  config/samples/milvus_metric_labels.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/podmonitor.go
  pkg/controllers/podmonitor_test.go
Labels: lgtm, approved, ci-passed, size/L

#337 fix force upgrade for 2 deploy mode
  pkg/controllers/deploy_ctrl_util.go
  pkg/controllers/deployment_updater.go
Labels: lgtm, approved, do-not-merge/hold, size/S

#338 golang to 1.24.2, milvus to 2.5.11, bump version
  .github/workflows/check-links.yml
  .github/workflows/mlc_config.json
  Makefile
  README.md
  apis/milvus.io/v1alpha1/zz_generated.deepcopy.go
  apis/milvus.io/v1beta1/zz_generated.deepcopy.go
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  docs/installation/installation.md
  go.mod
  go.sum
  pkg/controllers/milvus.go
Labels: approved, ci-passed, size/M

#343 fix changing mode while updating
  pkg/controllers/deploy_ctrl.go
  pkg/controllers/deploy_ctrl_test.go
Labels: lgtm, approved, ci-passed, size/M

#341 feat: change targetPort to int.
  Makefile
  apis/milvus.io/v1beta1/components_types.go
  apis/milvus.io/v1beta1/milvus_types.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/components.go
Labels: lgtm, approved, size/M
