Repository zilliztech/milvus-operator, pull requests merged in 2025-04, with the labels that each got.

#312 Go fmt all files
  apis/milvus.io/v1beta1/milvus_types.go
  apis/milvus.io/v1beta1/milvus_types_test.go
  apis/milvus.io/v1beta1/milvus_webhook.go
  apis/milvus.io/v1beta1/milvus_webhook_test.go
  pkg/config/config_test.go
  pkg/controllers/component_condition.go
  pkg/controllers/component_condition_test.go
  pkg/controllers/components_test.go
  pkg/controllers/conditions.go
  pkg/controllers/conditions_test.go
  pkg/controllers/configmaps.go
  pkg/controllers/configmaps_test.go
  pkg/controllers/dependencies_test.go
  pkg/controllers/deploy_ctrl.go
  pkg/controllers/deploy_ctrl_test.go
  pkg/controllers/deploy_ctrl_util.go
  pkg/controllers/deploy_ctrl_util_test.go
  pkg/controllers/deploy_mode_changer.go
  pkg/controllers/deploy_mode_changer_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/deployment_updater_test.go
  pkg/controllers/deployments.go
  pkg/controllers/deployments_test.go
  pkg/controllers/endpoint_check_cache.go
  pkg/controllers/endpoint_check_cache_test.go
  pkg/controllers/group_runner.go
  pkg/controllers/group_runner_test.go
  pkg/controllers/groups.go
  pkg/controllers/groups_test.go
  pkg/controllers/ingress.go
  pkg/controllers/ingress_test.go
  pkg/controllers/metrics.go
  pkg/controllers/milvus_test.go
  pkg/controllers/milvuscluster/convert_controller.go
  pkg/controllers/milvusupgrade_controller.go
  pkg/controllers/milvusupgrade_controller_test.go
  pkg/controllers/milvusupgrade_fsm_test.go
  pkg/controllers/podmonitor_test.go
  pkg/controllers/pvc.go
  pkg/controllers/rolling_mode_status_updater.go
  pkg/controllers/rolling_mode_status_updater_test.go
  pkg/controllers/rollout_util.go
  pkg/controllers/rollout_util_test.go
  pkg/controllers/services_test.go
  pkg/controllers/setup.go
  pkg/controllers/status_cluster_test.go
  pkg/controllers/utils.go
  pkg/controllers/utils_test.go
  pkg/external/kafka.go
  pkg/external/kafka_test.go
  pkg/external/minio.go
  pkg/external/minio_test.go
  pkg/external/pulsar_test.go
  pkg/util/testing_test.go
  test/batch-create/main.go
  test/batch-delete/main.go
Labels: lgtm, approved, ci-passed, size/L

#311 Enable etcd monitoring
  apis/milvus.io/v1beta1/components_types.go
  pkg/controllers/components.go
  pkg/controllers/podmonitor.go
  pkg/controllers/podmonitor_test.go
Labels: lgtm, approved, ci-passed, size/M

#319 fix pulsar-v2 chart path
  Makefile
  test/min-milvus-feature.yaml
Labels: lgtm, approved, ci-passed, size/L

#326 Consolidate semver libraries
  apis/milvus.io/v1beta1/milvus_types.go
  apis/milvus.io/v1beta1/milvus_types_test.go
  apis/milvus.io/v1beta1/milvusupgrade_webhook.go
  go.mod
  pkg/util/util.go
Labels: lgtm, approved, ci-passed, size/M

#327 milvus default to 2.5.10, bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#328 Fix deprecated aliyun library use
  go.mod
  go.sum
  pkg/external/iam/aliyun.go
Labels: lgtm, approved, ci-passed, size/M

#329 Fix deprecated functions
  pkg/external/iam/aliyun.go
  pkg/util/rest/rest_client.go
  pkg/util/rest/rest_client_test.go
Labels: lgtm, approved, ci-passed, size/S

#330 Enable golangci-lint
  .github/workflows/ci.yml
  .golangci.yml
  apis/milvus.io/v1alpha1/milvus_webhook.go
  apis/milvus.io/v1beta1/milvus_types.go
  apis/milvus.io/v1beta1/milvus_types_test.go
  apis/milvus.io/v1beta1/milvus_webhook.go
  apis/milvus.io/v1beta1/persistence_types.go
  main.go
  pkg/config/config.go
  pkg/controllers/components_test.go
  pkg/controllers/dependencies.go
  pkg/controllers/deploy_ctrl.go
  pkg/controllers/deploy_ctrl_util.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/deployments.go
  pkg/controllers/ingress_test.go
  pkg/controllers/milvus_controller.go
  pkg/controllers/milvus_controller_test.go
  pkg/controllers/milvuscluster/convert_controller.go
  pkg/controllers/milvusupgrade_fsm.go
  pkg/controllers/pvc.go
  pkg/controllers/setup.go
  pkg/controllers/status_cluster.go
  pkg/helm/values/values.go
  pkg/util/k8s_client_test.go
  pkg/util/util.go
  test/batch-delete/main.go
  tool/cp/main.go
  tool/merge/main.go
Labels: lgtm, approved, ci-passed, size/L

#331 Enable more linters
  .golangci.yml
  apis/milvus.io/v1beta1/milvus_webhook.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/controllers/component_condition.go
  pkg/controllers/components.go
  pkg/controllers/conditions.go
  pkg/controllers/dependencies_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/error_detail.go
  pkg/controllers/ingress.go
  pkg/controllers/milvus_controller.go
  pkg/controllers/milvuscluster/convert_controller.go
  pkg/controllers/podmonitor.go
  pkg/controllers/status_cluster.go
  pkg/external/iam/aliyun.go
  pkg/helm/helm.go
Labels: lgtm, approved, ci-passed, size/L
