Repository zilliztech/milvus-operator, pull requests merged in 2025-01, with the labels that each got.

#226 milvus default to 2.4.19, supports imagePullSecrets for operator
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/templates/deployment.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#227 Add cert secret name
  charts/milvus-operator/templates/deployment.yaml
Labels: lgtm, approved, ci-passed, size/XS

#228 milvus version to 2.4.20
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#229 iam-verify: add region param when provided in user.yaml
  pkg/external/iam/aliyun.go
  pkg/external/iam/aws.go
  pkg/external/iam/tencent.go
  pkg/util/yamlparser/file.go
  pkg/util/yamlparser/file_test.go
  test/user.yaml
  tool/iam-verify/main.go
Labels: lgtm, approved, ci-passed, size/S

#230 deploy_ctrl: fix stop during rolling in 2 deploy mode
  pkg/controllers/deploy_ctrl.go
  pkg/controllers/deploy_ctrl_test.go
Labels: lgtm, approved, ci-passed, size/XS

#231 bump version
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
Labels: lgtm, approved, ci-passed, size/M

#234 Support custom probes
  apis/milvus.io/v1beta1/components_types.go
  apis/milvus.io/v1beta1/zz_generated.deepcopy.go
  charts/milvus-operator/templates/crds.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
  pkg/controllers/components.go
  pkg/controllers/components_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/milvus_controller.go
  test/min-mc-feature.yaml
  test/min-milvus-feature.yaml
Labels: lgtm, approved, ci-passed, size/L

#233 deploy_ctrl: fix active configmap not work in manual mode
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/controllers/deploy_ctrl.go
  pkg/controllers/deploy_ctrl_test.go
  pkg/controllers/deploy_ctrl_util.go
  pkg/controllers/deploy_ctrl_util_test.go
  pkg/controllers/deployment_updater.go
  pkg/controllers/status_cluster.go
  pkg/controllers/status_cluster_test.go
Labels: lgtm, approved, ci-passed, size/L

#235 Fix some issues in manual mode
  pkg/controllers/deploy_ctrl.go
  pkg/controllers/deploy_ctrl_factory.go
  pkg/controllers/deploy_ctrl_test.go
  pkg/controllers/setup.go
Labels: lgtm, approved, ci-passed, size/M

#240 fix ci go version, milvus default to 2.4.21, bump version
  .github/workflows/ci.yml
  Makefile
  README.md
  charts/milvus-operator/Chart.yaml
  charts/milvus-operator/values.yaml
  deploy/manifests/deployment.yaml
  docs/installation/installation.md
  pkg/config/config.go
Labels: lgtm, approved, ci-passed, size/M

#214 pulsarv3: update values, default to 3.0.7, enabled for new milvus
  apis/milvus.io/v1beta1/dependencies_types.go
  apis/milvus.io/v1beta1/milvus_webhook.go
  apis/milvus.io/v1beta1/milvus_webhook_test.go
  charts/milvus-operator/templates/crds.yaml
  config/assets/charts/pulsar-v3-values.yaml
  config/crd/bases/milvus.io_milvusclusters.yaml
  config/crd/bases/milvus.io_milvuses.yaml
  deploy/manifests/deployment.yaml
Labels: lgtm, approved, ci-passed, size/L

#241 Update Go in CI to 1.23
  .github/dependabot.yml
  .github/workflows/ci.yml
Labels: lgtm, approved, do-not-merge/hold, size/M

#238 Add build info metric
  apis/milvus.io/v1alpha1/values_types_test.go
  apis/milvus.io/v1beta1/values_types_test.go
  go.mod
  go.sum
  pkg/controllers/metrics.go
Labels: lgtm, approved, do-not-merge/hold, size/M

#248 Update actions
  .github/workflows/chart-lint.yml
  .github/workflows/check-links.yml
  .github/workflows/ci.yml
  .github/workflows/dco.yml
  .github/workflows/deploy-manifest.yaml
  .github/workflows/docker-image.yml
  .github/workflows/main-latest.yml
  .github/workflows/release.yml
  .github/workflows/tool-docker-image.yml
  .github/workflows/weekly.yml
Labels: approved, do-not-merge/hold, size/L
